### ISSUE TITLE
Failed to build the site

### ISSUE THREAD

**Issue by stalkerGH** [thomasweitzel/zolarwind#4]
Hello.

I exported my Wordpress blog to .md files and like to experiment with Zola and Zolarwind theme. What trying to `zola serve` I got the message:

```
Building site...
Checking all internal links with anchors.
> Successfully checked 1 internal link(s) with anchors.
-> Creating 73 pages (0 orphan) and 2 sections
Error: Failed to serve the site
Error: Failed to render pager 7
Error: Reason: Failed to render 'blog.html'
Error: Reason: Variable `res.empty_page_summary` not found in context while rendering 'partials/list-element.html'
```

What should I check?

**Comment by thomasweitzel** [comment]
Hi! You found a bug: in the template `list-element.html` was a wrong reference to the resource value `res.empty_page_summary`, which should have been `res.empty_page_description`.
I have commited a fix to the repository.
You can also edit line 21 in `templates/partials/list-element.html` and replace `res.empty_page_summary` with `res.empty_page_description`.

**Comment by stalkerGH** [comment]
Thank you, your fix works :)
