### ISSUE TITLE
[Feature request] Add blog title to top bar

### ISSUE THREAD

**Issue by stalkerGH** [thomasweitzel/zolarwind#8]
I'd like to ask if it is possible to add option to enable/disable blog title to top grey bar on the blog's main site.

**Comment by thomasweitzel** [comment]
Thank you for your feature request. I appreciate your interest in customizing the Zolarwind theme.

To add the blog title from the configuration file above the menu bar, you can modify the theme to suit your preferences. Here’s a simple way to do it:

- Open the file `/themes/zolarwind/templates/partials/header.html`.
- Insert the following code after line 10:
  ```html
  <div class="pt-4 text-2xl font-bold text-gray-200">
    {{ config.extra.title | default(value="My Blog Title") }}
  </div>
  ```

This will display the blog title above the menu bar, making it more personalized.

While I love the clean look of the menu bar as it is and don't plan to modify the Zolarwind theme myself, I strongly encourage you to tailor the theme to your needs and preferences. Customizing your blog will make it truly unique and reflective of your style.

**Comment by stalkerGH** [comment]
Thank you for the hint and explaining of your motivation. I'd like to see blog title justified to right margin but I'll try to do it on my own :)

**Comment by thomasweitzel** [comment]
I'm closing this issue for now. If you have any further questions or suggestions, either reopen this issue or post a new one.
